$schemaver: 2.1
repo_url: # TODO: Update with GitHub repo URL
software:
  - name: # TODO: Update with software name (in ke-bab case)
    type: Web App
    assignment_group: gro:OIT-BYU-APPS-CUSTOM
    maintained_by:
      - # TODO: Update with NetID of maintainers
    developed_by_byu: true
    data_sensitivity: internal
    standard_change_template: # TODO: Update with standard change template alias
    technologies_used:
      - HTML
      - JavaScript
      - Vue
      - NuxtJS
      - Vuetify
      - CSS
      - Terraform
      - GitHub Actions
    stages:
      development:
        urls:
          physical_url: # TODO: Update with *.dev-oit-byu.amazon.byu.edu URL
        hosting_location: AWS
        aws_account: byu-oit-*-dev # TODO: Update with account name
      production:
        urls:
          physical_url: # TODO: Update with production URL
        aws_account: byu-oit-*-prd # TODO: Update with account name
