$schemaver: 2.1
repo_url: # TODO: Update with GitHub repo URL
software:
  - name: # TODO: Update with software name (in ke-bab case)
    deploy_to_cmdb: false
    type: Web App
    assignment_group: gro:OIT-BYU-APPS-CUSTOM
    notes:
    maintained_by:
      - # TODO: Update with NetID of maintainers
    developed_by_byu: true
    data_sensitivity: internal
    standard_change_template: # TODO: Update with standard change template alias
    microservice: false
    technologies_used:
      - HTML
      - JavaScript
      - Vue
      - NuxtJS
      - Vuetify
      - CSS
      - Handel
      - Handel-Codepipeline
      - AWS CodeBuild
      - AWS CodePipeline
      - AWS CloudFormation
    stages:
      development:
        urls:
          physical_url: # TODO: Update with *.dev-oit-byu.amazon.byu.edu URL
        hosting_location: AWS
        aws_account: dev-oit-byu
      production:
        urls:
          physical_url: # TODO: Update with production URL
        aws_account: # TODO: Update with account name
