---
version: 0.2

env:
  parameter-store:
    OAUTH_CLIENT_ID: /APPLICATION-NAME/oauth_client_id
    OAUTH_CALLBACK_URL: /APPLICATION-NAME/callback_url

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i -g yarn
  pre_build:
    commands:
      - yarn install --unsafe-perm
  build:
    commands:
      - 'echo "{\"autoRefreshOnTimeout\": true, \"clientId\": \"${OAUTH_CLIENT_ID}\", \"callbackUrl\": \"${OAUTH_CALLBACK_URL}\"}" > static/config.json'
      - yarn build
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - ./**/*
  base-directory: 'dist'
