version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Running npm install.
      - npm install
  build:
    commands:
      - echo Running tests
      - npm run test
      - echo Running linter
      - npm run lint
  post_build:
    commands:
      - echo Build completed
