---
version: 1
name: APPLICATION-NAME

pipelines:
  dev:
    phases:
      - type: github
        name: Github
        owner: byu-oit
        repo: REPO-NAME
        branch: dev
      - type: codebuild
        name: Build
        build_image: aws/codebuild/standard:2.0
        cache: s3
      - type: handel
        name: DevDeploy
        environments_to_deploy:
          - dev
  prd:
    phases:
      - type: github
        name: Github
        owner: byu-oit
        repo: REPO-NAME
        branch: master
      - type: codebuild
        name: Build
        build_image: aws/codebuild/standard:2.0
        cache: s3
      - type: handel
        name: PrdDeploy
        environments_to_deploy:
          - prd
